Compare sigmoid, tanh, relu activation functions by implement one hidden layer network (2 -> 12 -> 1) on make_circles dataset (n_samples= 1000, noise= 0.1). Train all three version with same hypeparameters, plot loss curve together, Plot decision boundaries as well for each...

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import make_circles

In [7]:
print(make_circles)

<function make_circles at 0x0000025B26607920>


In [9]:
df= make_circles(n_samples= 1000)

In [10]:
print(df)

(array([[-0.36812455,  0.92977649],
       [ 0.43711577,  0.89940525],
       [-0.38540294, -0.70104534],
       ...,
       [-0.6034011 , -0.5252686 ],
       [-0.93873386,  0.34464292],
       [-0.66601187, -0.74594115]], shape=(1000, 2)), array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 

In [13]:
from sklearn.model_selection import train_test_split

In [22]:
X= df[0]
y= df[1]

print(X)

[[-0.36812455  0.92977649]
 [ 0.43711577  0.89940525]
 [-0.38540294 -0.70104534]
 ...
 [-0.6034011  -0.5252686 ]
 [-0.93873386  0.34464292]
 [-0.66601187 -0.74594115]]


In [23]:
print(y)

[0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 0 1 1
 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 1
 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 1 0
 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1
 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0
 0 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 1 1 1
 0 0 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0
 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1
 0 1 1 0 1 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0
 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0
 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 0
 1 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0
 0 1 0 0 0 0 1 0 0 0 1 1 

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(X, y)

In [33]:
print(np.shape(X_train), np.shape(X_test), np.shape(y_train), np.shape(y_test))

(750, 2) (250, 2) (750,) (250,)


In [ ]:
print(X_train, X_train, y_train, y_test)

[[ 0.23763327  0.76389164]
 [-0.73751312  0.67533281]
 [-0.6472136  -0.4702282 ]
 ...
 [-0.91524117 -0.40290644]
 [ 0.62276984 -0.50215309]
 [-0.79488905 -0.09028511]] [[ 0.23763327  0.76389164]
 [-0.73751312  0.67533281]
 [-0.6472136  -0.4702282 ]
 ...
 [-0.91524117 -0.40290644]
 [ 0.62276984 -0.50215309]
 [-0.79488905 -0.09028511]] [1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 1 0 1
 1 0 1 0 0 1 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 0 1 0 0 1 0 0 1 0
 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 1
 1 0 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 0
 1 0 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1
 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1 0 0 1 0
 1 0 1 1 0 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 1 1
 0 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 0 0
 1 0 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 1 0 0

### (2 -> 12 -> 1)

In Input layer, W1 and b1 exist and have 2*12 and 1*12 order
        act func are sig, tanh and relu
In Hidden layer, W2 and b2 exist and have 12*1 and 1*1 order
        act func as sig
In Output layer, y of order 1*1

In [58]:
def sig(x):
    return 1/(1+np.exp(-x))

class NN:
    def __init__(self, act="sig", lr=0.01):
        self.lr= lr
        self.act= act
        np.random.seed(0)
        self.W1= np.random.randn(2,12)*0.1
        self.b1= np.zeros((1,12))
        self.W2= np.random.randn(12,1)*0.1
        self.b2= np.zeros((1,1))
    
    def forward(self,X):
        self.H1= X @ self.W1 + self.b1
        self.A1= self.act(self.Z1)
        self.H2= self.A1 @ self.W2 + self.b2
        self.A2= sig(self.Z2)
        return self.A2

    def backward(X, W, b):
        # w_new = w - lr * grd(x)
        W= W - self.lr * self.act_d(X)
        b= b - self.lr * self.act_d(X)
        return  W, b

    
    def train(X, y):
        losses= []
        for i in range(10000):
            y_pred= self.forward(X)
            losses= self.loss(y_pred, y)
            print(losses)
            self.backward(X, W, b)
            acc= self.accuracy(y_pred, y)

    def act(self,x):
        if self.act== "sig":
            return 1/(1+np.exp(-x))
        if self.act== "tanh":
            return np.tanh(x)
        if self.act== "relu":
            return np.maximum(0,x)
        
        
    def act_d(self,x):
        if self.act== "sig":
            s = 1/(1+np.exp(-x))
            return s*(1-s)
        if self.act== "tanh":
            return 1 - np.tanh(x)**2
        if self.act== "relu":
            return (x>0)
        
    def accuracy(y_pred, y):
        count= 0
        for i,j in (y_pred,y):
            if i==j:
                count+= 1
        return count/10
    
    def loss(y_pred, y):
        #  e = (y_pred)*np.log(1 - y_train) + (1 - y_pred)*np.log(y_train)
        e= 0
        for i,j in zip(y_pred, y):
            e+= -((i)*np.log(1- j) + (1- i)*np.log(j))
        return e

In [56]:
NeuralN= NN()
NeuralN.train(X_train)

NameError: name 'self' is not defined

In [57]:
import matplotlib.pyplot as plt